In [3]:
from src.app.utils import init_llm, init_vector_store
from langchain import hub
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough

In [4]:
llm = init_llm()
vector_store = init_vector_store()

Fetching 5 files: 100%|██████████| 5/5 [00:00<?, ?it/s]
INFO:httpx:HTTP Request: GET http://localhost:6333/collections/tbibi_app_rag_app_chat "HTTP/1.1 200 OK"


In [6]:
retriever = vector_store.as_retriever()
prompt = hub.pull("rlm/rag-prompt")


def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)


rag_chain = (
    {"context": retriever | format_docs, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

rag_chain.invoke("Who is amine mekki ?")

c:\Users\Amine\anaconda3\envs\tbibi_rag\Lib\site-packages\langsmith\client.py:312: LangSmithMissingAPIKeyWarning: API key must be provided when using hosted LangSmith API
  warnings.warn(
INFO:httpx:HTTP Request: POST http://localhost:6333/collections/tbibi_app_rag_app_chat/points/query "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"


"Amine Mekki is a machine learning engineer with a background in computer science and biomedical engineering. He has worked in various roles, including data scientist at Sanofi and Vaisala, and MLOps engineer at Ecole des Mines d'Alès. He holds MSc degrees in Computer Science & Machine Learning from IMT Mines Alès and Biomedical Engineering from the University of Montpellier."

: 

In [2]:
pip install pandas


  Using cached pandas-2.2.2-cp311-cp311-win_amd64.whl.metadata (19 kB)
  Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached pandas-2.2.2-cp311-cp311-win_amd64.whl (11.6 MB)
Using cached tzdata-2024.1-py2.py3-none-any.whl (345 kB)
Note: you may need to restart the kernel to use updated packages.


In [3]:
import pandas as pd
a = {
    "a" : [1,2,3],
    "b" : [4,5,6]
}

dt = pd.DataFrame(a)

In [8]:
import numpy as np

# Defining the matrices
A = np.array([[1, 1, 2]])
B = np.array([[1], [-1], [1]])
C = np.array([[1, 3, 1], [1, 1, 1]])
D = np.array([[0, 1], [1, -1], [2, 1]])
E = np.array([[5, -1], [3, 1]])

# Performing the calculations for the assertions

# 1. A + B cannot be performed as they have incompatible shapes, skipping this.
# 2. AB multiplication
AB = np.dot(A, B)

# 3. CA multiplication
CA = np.dot(C, A.T)

# 4. CD multiplication
CD = np.dot(C, D)

AB, CA, CD

(array([[2]]),
 array([[6],
        [4]]),
 array([[ 5, -1],
        [ 3,  1]]))

In [9]:
# Defining the matrices A and B
A = np.array([[1, 1, 2], [-1, 0, 2], [1, -1, 1]])
B = np.array([[1, 1, -1], [1, 1, 3], [-1, 1, 0]])

# 1. Calculate 2A + 3B
A_2B_3 = 2 * A + 3 * B

# 2. Calculate A - B
A_minus_B = A - B

# 3. Calculate AB (matrix multiplication)
AB = np.dot(A, B)

# 4. Calculate BA (matrix multiplication)
BA = np.dot(B, A)

A_2B_3, A_minus_B, AB, BA

(array([[ 5,  5,  1],
        [ 1,  3, 13],
        [-1,  1,  2]]),
 array([[ 0,  0,  3],
        [-2, -1, -1],
        [ 2, -2,  1]]),
 array([[ 0,  4,  2],
        [-3,  1,  1],
        [-1,  1, -4]]),
 array([[-1,  2,  3],
        [ 3, -2,  7],
        [-2, -1,  0]]))

In [21]:
A = np.array([1, 2, 4])
B = np.array([[0], [1], [-1]])
C = np.array([[1, -1, 1], [0, 0, 1]])
D = np.array([[1, -1, 0], [2, 1, 1], [0, 2, 1]])

# 1. Calculate A + B^T
A_plus_B_T = A + B.T

# 2. Calculate B^T * B
B_T_B = np.dot(B.T, B)

B_T_B, A_plus_B_T

(array([[2]]), array([[1, 3, 3]]))

In [20]:
# 3. Calculate A^T * C
A_T_C = np.dot(A.T, C)

# 4. Calculate C^T * D
C_T_D = np.dot(C.T, D)

A_plus_B_T, B_T_B, A_T_C, C_T_D

ValueError: shapes (3,) and (2,3) not aligned: 3 (dim 0) != 2 (dim 0)